### ISSUE TITLE
Should this note provide an abstract model?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/ruby-tts-req#13]
The scope of this note is restricted to user requirements.  Although I do not think that we should describe implementation mechanisms such as APIs, it might be a good idea to provide an abstract model as well.  The abstract model should (1) provide initialization for Pronunciation Lexicon Specification (PLS), (2) make clear whether ruby base, ruby text, or both are passed to TTS engines, and (3) maintain (ruby base, ruby text) pairs for future processing.

**Comment by fantasai** [comment]
@murata2makoto I think that should be out of scope for this note. It should focus on helping engineers understand the user requirements and current problems. Once you're defining a data model, even if it is not including a concrete API, that becomes a document about solutions, and probably belongs on REC track. Also it requires a lot more discussion among the implementation teams, about what's possible and what's likely and what's best; increasing the scope so much will prevent the note from being completed and will create too much confusion where the note is supposed to create clarity.

**Comment by murata2makoto** [comment]
@fantasai Agreed.
