### ISSUE TITLE
make consistent markup for pronunciations

### ISSUE THREAD

**Issue by himorin** [w3c/ruby-tts-req#18]
There are several styling of 'pronunciations' in current draft, such as just placed as a text, quoting, or as `/xxx/` (phonetic sign mark).
It should be better to have the same styling over all pronunciations, to let readers know easily.

- which one should be the best option? (any example in other publications?)
- (I would take an action to work after styling is decided)

**Comment by murata2makoto** [comment]
IPA phonetics are most expressive but do people know IPA?  Japanese learn phonetics (but cannot pronounce them correctly).  How do Westerners feel?

**Comment by himorin** [comment]
Actually, I meant only the display styling side. Such as:

- in section 2.2, all capital are used for readings like `SEIMEI `, although 3.3.2 uses small letters as `"seimei"`
- in section 3.1, simply hiragana text are used for readings like `にわとりでもかって、しんせんなたまごをうましてたべようとおもいました`
- in section 3.1.4, normally capitalized English text with quoted are used, like `"Tokugawa Yoshinobu 1837-1913 Edo Bakufu Saigono Shougun"`, although 3.2.4 uses katakana as `"1837-1913 エドバクフサイゴノショウグン" `

also for phonetics, 3.2.1 uses `/xxx/` like `わ (/wa/) or は (/ha/)`, 3.2.2 uses `"xxx"` like `いのち ("inochi")`.

**Comment by murata2makoto** [comment]
@himorin 
> in section 2.2, all capital are used for readings like SEIMEI , although 3.3.2 uses small letters as "seimei"

SEIMEI is probably better.

> in section 3.1, simply hiragana text are used for readings like にわとりでもかって、しんせんなたまごをうましてたべようとおもいました

After all, this example is not very understandable for those who don't understand Japanese.  I think that (1) another example understandable for English speakers is necessary and that (2) since the current example in 3.1 does not have to be understandable for English speakers, we can use hiragana freely here.

> in section 3.1.4, normally capitalized English text with quoted are used, like "Tokugawa Yoshinobu 1837-1913 Edo Bakufu Saigono Shougun", although 3.2.4 uses katakana as "1837-1913 エドバクフサイゴノショウグン"

Yes, this is ugly.  We should be consistent.

> also for phonetics, 3.2.1 uses /xxx/ like わ (/wa/) or は (/ha/), 3.2.2 uses "xxx" like いのち ("inochi").

How about /wʌ'/ for は as a particle, and /hʌ'/, otherwise?  Also, /é/ for へ as a particle, and /hé/, otherwise?

**Comment by himorin** [comment]
For the last point, considering both IPA phonetics and hiragana are not widely understandable by reader, I suppose we could just use hiragana (or romanization of Japanese?) to show their pronunciation, just to tell 'two readings are different'.

For third point, I would work on PR once solid target way is pointed.

**Comment by murata2makoto** [comment]
let's use hiragana consistently and see what happens.  @himorin, could you create a pull request for this?

**Comment by murata2makoto** [comment]
Done by [this commit](https://github.com/w3c/ruby-t2s-req/commit/21630ae8507365f94d7532fb5de1662a98d57939).
