### ISSUE TITLE
Two more references: mechanisms for using SSML or PLS from HTML

### ISSUE THREAD

**Issue by murata2makoto** [w3c/ruby-tts-req#23]
Reference two specifications in [Section 5](https://w3c.github.io/ruby-t2s-req/#alternatives-to-ruby).

- [Specification for Spoken Presentation in HTML](https://www.w3.org/TR/spoken-html/)
- [EPUB 3 Text-to-Speech Enhancements 1.0](https://www.w3.org/TR/epub-tts-10/)

They provide mechanisms for using SSML or PLS from HTML.

**Comment by murata2makoto** [comment]
Oops, EPUB 3 Text-to-Speech Enhancements 1.0 was already taken care of by #22.

**Comment by murata2makoto** [comment]
@himorin 

I would like to reference EPUB 3.2 as well but how can I do so?  Specref does not appear to have an entry for it.

**Comment by himorin** [comment]
[could not find in specref search](https://www.specref.org/?q=epub), so need to add via localbiblio.
localbiblio of EPUB 3.2 is [here](https://github.com/w3c/epub-specs/blob/main/archive/epub32/spec/common/js/biblio.js), and picked some and added as #25. Please feel free to overwrite the PR.

**Comment by himorin** [comment]
I believe this is fixed per PR #26?
