### ISSUE TITLE
Add README?

### ISSUE THREAD

**Issue by himorin** [w3c/ruby-tts-req#27]
Are we better to add README.md at the top level? (I've totally forgot this at the time of initial creation...)

**Comment by murata2makoto** [comment]
What should we describe in README.md?  How about this?

- Which W3C group does this?
- The location of the Editor's draft and the WD 
- Contributing to the Repository
- Code of Conduct

**Comment by himorin** [comment]
I've totally off from this issue, sorry.
It could be simple as simple-ruby one, and we could redirect 1st/3rd/4th point with referring JLReq repository (e.g. just by linking; should be the same)??

**Comment by murata2makoto** [comment]
I have the REAME.md of epub-specs in mind.  See https://github.com/w3c/epub-specs

**Comment by himorin** [comment]
I suppose epub-specs one corresponds one in jlreq repo for us...
how about as #30?
