### ISSUE TITLE
Editorial issue in the example

### ISSUE THREAD

**Issue by xfq** [w3c/ruby-tts-req#3]
Sorry for being pedantic, but I think we should either change 最後 to 初期, or change 家康 to 慶喜 (and change the years) in https://w3c.github.io/ruby-t2s-req/#interlinear-notes-0 to reflect the correct history.

**Comment by xfq** [comment]
(There are similar issues in https://w3c.github.io/ruby-t2s-req/#interlinear-notes-1 and https://w3c.github.io/ruby-t2s-req/#interlinear-notes-2)

**Comment by himorin** [comment]
ah, yes. I've fixed some, but seems missed to pick all..
I'll grep with some words, and fix them all. (also related to https://github.com/w3c/jlreq/issues/313 )
