### ISSUE TITLE
Should simple ruby be referenced?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/ruby-tts-req#35]
The JLreq TF decided to discontinue the development of simple-ruby, as shown in [JLReq TF meeting notes 2023-5-30](https://github.com/w3c/jlreq/issues/369).  Now, "Text to Speech of Electronic Documents Containing Ruby: User Requirements" references [the abandoned draft](https://www.w3.org/TR/simple-ruby/).  Should we drop this reference?

**Comment by himorin** [comment]
I have no position on this.
it's NOTE which doesn't intend to promote as statement, and also all references are informative.

**Comment by murata2makoto** [comment]
JLTF abandoned some terms defined in simple-ruby.   If this document references simple-ruby, will people be confused?

**Comment by murata2makoto** [comment]
[Dropped the references to simple-ruby.](https://github.com/w3c/ruby-t2s-req/commit/8c670d7429b3b380696cdf86f86c5feeae17c9db)
