### ISSUE TITLE
Proposed Subsections for Zaima Annotation

### ISSUE THREAD

**Issue by dyacob** [w3c/ruby-tts-req#41]
## 2.7 Zaima, background

The primary purpose of zaima annotation is to indicate vocal inflection and intonation of the base text to
produce a melody when a complete passage is vocalized. Zaima is the annotation practice of the Ge'ez language
hymnal tradition which in layout is visually identical to Furigana annotation and shares formatting requirements.

The zaima annotation elements may be one of 8 basic shape notes, or will be a one or two letter abbreviation of a word
from a large vocabulary. These elements cue the reader for how to inflect their voice when reading the base text
aloud. A hymn may be recited under different melodies depending on the occasion. These alternative vocalizations
will draw from separate vocabulary collections and in writing will be laid out above the base text on higher level
rows.

Multiple rows of annotation are common in the written zaima hymnal practice. It is crucial for the reader to be aware of
the row context to then be able to decode the abbreviations under the proper vocabulary set. Identical abbreviations can
be found across vocabularies, but referencing entirely different words with different inflection patterns. For the
execution of this decoding, awareness of the annotation row context is just as crucial when only a single row is present.

Here are some examples of zaima that highlight the importance of identifying the context of the annotation row:

<ul>

<li>
በከ<ruby><rb>መ</rb><rt>᎑</rt></ruby>፡አር<ruby><rb>ኃ</rb><rt>ቁ</rt></ruby><ruby><rb>ወ</rb><rt align="right">ር</rt></ruby>፡ዳ<ruby><rb>ን</rb><rt>ዮ</rt></ruby>ኤ<ruby><rb>ል</rb><rt>ዑ</rt></ruby>፡<ruby><rb>ነ</rb><rt>᎐</rt></ruby>ቢ<ruby><rb>ይ</rb><rt>ርስ</rt></ruby>፡መ<ruby><rb>ሣክ</rb><rt>አክ</rt></ruby><ruby><rb>ወ</rb><rt>᎑</rt></ruby>፡ቤ<ruby><rb>ቱ</rb><rt>ዕት</rt></ruby>፡  <br>Here the “ዑ” abbreviation is short for “ወይወው<u>ዑ</u>” under the Digua - Ge’ez mode vocabulary.
</li>
<li>
<ruby><rb>ዖ</rb><rt>᎑</rt></ruby><ruby><rb>ደ</rb><rt>ዑ</rt></ruby>፡አድ<ruby><rb>ያ</rb><rt>᎖</rt></ruby><ruby><rb>መ</rb><rt>ዊ</rt></ruby>፡ዮርዳኖ<ruby><rb>ስ</rb><rt>ይደ</rt></ruby>፡እንዘ፡<ruby><rb>ይ</rb><rt>᎖</rt></ruby>ጸር<ruby><rb>ሕ</rb><rt>ኖስ</rt></ruby>፡  <br>Here the “ዑ” abbreviation is short for “በግ<u>ዑ</u>” under the Digua - Araray mode vocabulary.
</li>
<li>
  <ruby><rb>ኅ</rb><rt>᎐</rt></ruby>ድግ<ruby><rb>ዎ</rb><rt>ዑ</rt></ruby>፡ወመንን<ruby><rb>ዎ</rb><rt>ይደ</rt></ruby>፡ለ<ruby><rb>ዝ</rb><rt>በዮ</rt></ruby>ዓለ<ruby><rb>ም</rb><rt>ኖስ</rt></ruby>፡  <br>Here the “ዑ” abbreviation is short for “<u>ዑ</u>ቁ” under the Tsome Digua - Araray mode vocabulary.
</li>

</ul>

## 3.1.7 Zaima annotation, when both read aloud

The option of reading both aloud is sensible and assumed. Since the role of zaima annotation is to
provide inflection guidance, the annotation is implicit in the vocalization.  However, if the annotation is
read aloud verbatim, without tonal interpretation, along with the base, the reading does not make any sense
at all and is analogous to the Furigana case.

## 3.2.7 Zaima annotation, when zaima annotation read aloud

The option of reading aloud zaima annotations only interferes with the readers' understanding significantly.

Since zaima annotation relies on a system of abbreviation, a verbatim reading of annotation would be
understandable only to expert practitioners. Learners would likely need to hear the abbreviations expanded
back into the original term(s) -which in turn requires awareness of the row context. This capability may indeed
be an aid in zaima training. However, the practical benefit that can be derived from reading the zaima annotation
aloud assumes that the reader is also simultaneously aware of the base text when hearing the annotation.

## 3.3.7 Zaima annotation, when bases read aloud

The option of reading zaima bases only provides a perfectly understandable result. However,
since the vocal inflection cues are ignored, the melodic intent of the author is not conveyed.

**Comment by xfq** [comment]
More background on Zaima: https://w3c.github.io/elreq/zaima/

/cc @murata2makoto @frivoal

**Comment by murata2makoto** [comment]
Is it possible to distinguish Zaima ruby and CJK ruby by examining UCS code points?

**Comment by dyacob** [comment]
@murata2makoto yes, the practice has changed little in 1500 years and utilizes symbols from the Ethiopic Basic range (U+1200 - U+137C) which will be found in both base text and annotation.  Then annotation additionally will have notation symbols from the Ethiopic Supplement range (U+1390 - U+1399).  Then no other symbols.  Conversely, symbols from these ranges should not be found in CJK ruby in realistic samples.

**Comment by kidayasuo** [comment]
It appears that Zaima is more akin to an early form of musical score or notation. As such, it would fall outside the scope of the ruby-tts document, at least in its current form. However, should there be a significant reason to document the requirements for Zaima, the ruby-tts document may be the most suitable place for it. Should we choose to include it, it could lead to an increase in requests to incorporate additional musical notations into the document in the future.

![image](https://github.com/w3c/ruby-t2s-req/assets/33173251/2cc962d8-8a14-41d8-ba8e-95aa1248c6c4)
The image is one of ancient musical score from Japan: from https://blog.goo.ne.jp/hirochan1990/e/a624f8c71fadfb4395ce0f5f94fcbe42

**Comment by dyacob** [comment]
@kidayasuo I think that you are correct here.  While Zaima appears to share the layout requirements of Ruby annotation, the TTS use case seems not applicable, the Zaima base text would need to be sung melodically as guided by the annotation which is a different problem - _Text-To-Song?_  🙂

Thinking about it a little more, in a Text-To-Speech scenario, the Zaima annotation could be **ignored** and the base text vocalized in a regular voice.

**Comment by kidayasuo** [comment]
Thank you @dyacob for your thoughts and additional information. I hope there is a place for documenting requirements for Zaima annotation.

If Zaima should be ignored, and if it uses the same ruby tag, we might need to somehow flag it so that TTS appropriately ignores it. @murata2makoto is there such a mechanism, do you know?

**Comment by kidayasuo** [comment]
Closing as Zaima is not a scope of ruby-tts document, as agreed.

**Comment by kidayasuo** [comment]
Additional note: We can ignore Zaima notation by adding [aria-hidden="true"](https://www.w3.org/TR/wai-aria-1.2/#aria-hidden) attribute to the element.
