### ISSUE TITLE
Scope: Japanese only?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/ruby-tts-req#45]
Should this document cover ruby in Japanese contents or should it cover mainland China, Taiwan, and Zaima?  CLreq uses different terms for describing ruby.  Zaima requires some features (Rows 2 and 3) not required by Japanese or Chinese/Taiwanese text.

**Comment by murata2makoto** [comment]
In a JLreq meeting on 2024-02-06, we agreed not to make this note specific to the Japanese language, especially because CLreq is going to use the term "ruby".

**Comment by r12a** [comment]
Just a passing note to mention that Mongolian also uses ruby sometimes (because it can be difficult to guess the pronunciation of some letters just by looking at them).

See an example at https://github.com/w3c/type-samples/issues/5
