### ISSUE TITLE
Editorial: Clarify text-to-speech acronym "T2S" is also known as "TTS"

### ISSUE THREAD

**Issue by cookiecrook** [w3c/ruby-tts-req#5]
I would recommend expanding most instances of the "T2S" acronym in favor of the phrase "text-to-speech."

Despite working in assistive technology, I don't recall ever seeing the "T2S" in that context. (Though the similar acronym "TTS" comes up commonly in my circle.) Rather than prefer one acronym over the other, I'd recommend making "text-to-speech" the preferred term in prose, with a definition linked that explains the context and acronyms. (ReSpec glossary link?) Definition could also like terms like "Speech Synthesis" and "generated computer speech" that others may know.

**Comment by himorin** [comment]
Thank you for pointing, and `T2S` is used only once in text (excl. shortname), and I would also recommend @murata2makoto to expand the one.

**Comment by murata2makoto** [comment]
I agree to use  "text-to-speech" instead of T2S.  Is the repository name "ruby-t2s-req" ok?
