### ISSUE TITLE
Consider including English variants of the Ruby examples to make them more understandable to a non-Japanese-speaking audience.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/ruby-tts-req#6]
Consider including English variants of the Ruby examples to make them more understandable to a non-Japanese-speaking audience.

Some specific examples from the comments in https://github.com/w3c/aria/issues/1620:
- The Dewanai example plus a similar English phrase: "My name is <ruby>Knot<rt>not</rt></ruby>"
- Difficult-to-pronounce Species or Pharmaceutical names may be appropriate to include here, such as <ruby>oxoerythromycin<rt>oxo-eur-ithro-mycin</rt></ruby> or <ruby>oxoerythromycin<rt>/ɒk.sə(ʊ).ɪˌɹɪθ.ɹə(ʊ)ˈmʌɪ.sɪn/</rt></ruby>.
- Your example of <ruby>enemy<rt>friend</rt></ruby> meaning "frenemy"
- Another example from a colleague: 丁度良い所に<ruby>常連<rt>カモ</rt></ruby>が来たよ (look, here comes a regular customer now) where 常連 (regular customer)’s ruby says カモ (easy target/victim). English equivalent "look, here comes <ruby>a regular customer<rt>(an easy target / victim)</rt></ruby>"
- <ruby>背景<rt>バック</rt></ruby> (<ruby>HAIKEI<rt>back</rt></ruby> or maybe <ruby>HAIKEI<rt>back-u?</rt></ruby>)

**Comment by xfq** [comment]
Hmm... I read the document in https://w3c.github.io/ruby-t2s-req/ carefully from beginning to end, but didn't find the Dewanai example and the frenemy example.

**Comment by xfq** [comment]
I found it here, though: http://www.asahi-net.or.jp/~eb2m-mrt/rubytest.html

**Comment by himorin** [comment]
Dewanai example was used in Murata-san's presentation for ruby a11y.

**Comment by murata2makoto** [comment]
I am sorry.  [My presentation in the ARIA session](https://1drv.ms/p/s!An5Z79wj5AZBkaxygsvcyNZp3O-_0g?e=gGKFM1) and [that in the I18N session](https://1drv.ms/p/s!An5Z79wj5AZBkax0dhb5thC6D1Ow8w?e=k8YiaZ) during the last TPAC has the Dewanai example and the frenemy example.

Historical anecdote: The Dewanai example was originally created by Kida-san in 1998 when he tried to stop the addition of Unicode characters for ruby.

**Comment by murata2makoto** [comment]
Most of the examples mentioned in this issue have been added to the latest draft.
