### ISSUE TITLE
Possible readings of a kanji character

### ISSUE THREAD

**Issue by murata2makoto** [w3c/ruby-tts-req#7]
@aleventhal wrote as [a comment to another issue in a different repository](https://github.com/w3c/aria/issues/1620#issuecomment-957943879): 

MM>Their implementations examine code points of base characters.

>Can we get an understanding of where this heuristic falls down? Or, if it's highly accurate, then do we actually need markup to differentiate between para-ruby and general-ruby?

[This web page](https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/kanji/joyokanjisakuin/index.html) by a Japanese ministry shows which kanji can be read how.  But for pedagogical reasons, it oversimplifies the mess of kanji. For example, consider 生, which is for the first grade in Japanese elementary schools.  Only 12 phonetics of this kanji character are listed.

But the reality is different.  Difficulties in reading a kanji character in a particular context do not necessarily relate to the difficulties of that kanji character. 

There are more than 100 ways of reading this character: 生きる(ikiru), 生える(haeru), 生む(umu), 先生(sensei), 生も の(nama mono), 生糸(kiito), 生い立ち(oitachi), 弥生(yayoi), 生憎 (ainiku), 生さぬ仲(nasanu naka), 苔の生すまで(kokeno musumade) , 生簀 (ikesu), 早生(wase), 晩生(okute), 芝生(shibafu), 生業(nariwai), 生粋 (kissui), and so forth.  If we consider proper names such as 福生, 羽生, 生保内, and 壬生, things will become even more difficult.  I do not believe that the required heuristics will be written down and implemented in the near future.

[This page](https://www.mext.go.jp/a_menu/shotou/new-cs/youryou/syo/koku/001.htm) shows which kanji is taught in which grade in K12.  A DAISY reader uses this list for hiding kanji characters below the specified grade.  But if we really want to mimic printed textbooks, we will have to know which kanji is taught in which semester.   Different textbooks teach kanji characters in different orders.

**Comment by aleventhal** [comment]
@murata2makoto thank you. I now want to learn to read Japanese! Probably won't happen in time to fix this bug tho :)

Here's another question. You mentioned that assuming we can read the `<rt>` text would be catastrophic, because it could change the meaning. However, are there times that it would be better, and is that something we might want to put in author control via a semantic?

**Comment by murata2makoto** [comment]
To my surprise, ChatGPT (V3.5) is already quite good at reading the above examples!

**Comment by murata2makoto** [comment]
This issue does not contain proposed changes.  Moreover, as demonstrated by ChatGPT, it is possible to handle many possible readings of 生 automatically.  I will close this issue.
